# Generated by Django 5.2.6 on 2025-09-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
