# Generated by Django 5.2.6 on 2025-09-18 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_alter_vote_unique_together_vote_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spoiled_votes',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.candidate_position'),
        ),
    ]
