# Generated by Django 5.2.6 on 2025-09-18 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_spoiled_votes_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spoiled_votes',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.candidate_position'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.candidate_position'),
        ),
    ]
