# Generated by Django 5.2.6 on 2025-09-18 09:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_alter_spoiled_votes_position_alter_vote_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate_position',
            options={'ordering': ['added_on']},
        ),
        migrations.AlterUniqueTogether(
            name='spoiled_votes',
            unique_together={('position', 'voter')},
        ),
    ]
