# Generated by Django 5.2.6 on 2025-09-19 11:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_alter_candidate_position_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='spoiled_votes',
            unique_together={('election', 'voter')},
        ),
        migrations.RemoveField(
            model_name='spoiled_votes',
            name='position',
        ),
    ]
