# Generated by Django 5.2.6 on 2025-09-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0007_alter_spoiled_votes_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='abstain',
            field=models.BooleanField(default=True),
        ),
    ]
