# Generated by Django 5.2.6 on 2025-09-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0008_election_abstain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='abstain',
            field=models.BooleanField(default=False),
        ),
    ]
