# Generated by Django 5.2.6 on 2025-09-19 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0009_alter_election_abstain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='abstain',
        ),
    ]
