# Generated by Django 5.2.6 on 2025-09-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_voted',
            field=models.BooleanField(default=False),
        ),
    ]
