# Generated by Django 5.2.6 on 2025-09-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='/assets/img/prof.png', null=True, upload_to='profile/pictures/'),
        ),
    ]
