# Generated by Django 5.2.6 on 2025-09-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='/profile/pictures/prof.png', upload_to='profile/pictures/'),
        ),
    ]
