# Generated by Django 5.2.6 on 2025-09-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('REGISTER', 'User Registration'), ('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('VOTE', 'Vote Cast'), ('OTP_VERIFY', 'OTP Verification'), ('ADMIN_ACTION', 'Admin Action')], max_length=5000),
        ),
    ]
