# Generated by Django 5.2.6 on 2025-09-22 12:56

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_auditlog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingid',
            name='expires_at',
            field=models.DateTimeField(default=authentication.models.default_end_datetime),
        ),
        migrations.AlterField(
            model_name='votingid',
            name='created_at',
            field=models.DateTimeField(default=authentication.models.TimeStampedModel),
        ),
    ]
